import type { FormData } from './types';

function uid() {
  return Math.random().toString(36).slice(2, 9);
}

export const defaultFormData: FormData = {
  name: 'Kayan Shah',
  location: 'London',
  typingLines: "Hi there! I'm Kayan 👋\nBuilder. Leader. Engineer.\nWelcome to my GitHub!",
  tagline: 'Founder. Team Leader. Engineer. Building things that compete on a world stage.',
  bio: "I'm **Kayan Shah** - a student engineer and programmer based in London. I build software and hardware that makes a real-world impact: from Python tools and Swift apps, to **international electric cars and world-championship winning robots**. Currently leading teams heading just back from the **VEX World Championships 2026**, fresh from the **Greenpower International Finals 2025**.",
  githubUsername: 'KayanShah',
  email: 'hi@kayanshah.com',
  whatIBuildLeftTitle: 'AI & Software',
  whatIBuildLeftDesc: 'Python, Swift/SwiftUI, and LLMs. Focused on tools that are accessible and practical.',
  whatIBuildRightTitle: 'Engineering & Robotics',
  whatIBuildRightDesc: 'Full-scale electric cars to VEX competition robots. CAD, electronics, and competitive strategy.',
  achievements: [
    { id: uid(), emoji: '🤖', title: '**VEX World Championship Qualifier** — Team 34071B (St. Louis, 2026)', scope: '🌍 Global' },
    { id: uid(), emoji: '🎖️', title: '**VEX World Championship Judges Award** (St. Louis, 2026)', scope: '🌍 Global' },
    { id: uid(), emoji: '🏎️', title: '**Greenpower International Finalist** (2025)', scope: '🌍 Global' },
    { id: uid(), emoji: '🏆', title: '**Make:Able DT Challenge World Finalist**', scope: '🌍 Global' },
    { id: uid(), emoji: '💻', title: '**#1 UK VEX Virtual Robot Program** (MS/HS) with [**@PanshulVempalli**](https://github.com/PanshulVempalli) · **#11 Globally** (MS)', scope: '🇬🇧 National and<br>🌍 Global' },
    { id: uid(), emoji: '📜', title: '**CREST Silver & Bronze Awards** (Individual & Team)', scope: '🇬🇧 National' },
    { id: uid(), emoji: '🦾', title: '**VEX UK Nationals Qualifier** — Team 34071B (Telford, 2026)', scope: '🇬🇧 National' },
    { id: uid(), emoji: '🥇', title: '**Greenpower Portfolio Award** — 1st Place (Regional)', scope: '🇬🇧 Regional' },
    { id: uid(), emoji: '🏅', title: '**VEX Judges Award** — 1st Place (Regional)', scope: '🇬🇧 Regional' },
    { id: uid(), emoji: '📋', title: '**HackerRank Python Certificate** — [View Certificate](https://www.hackerrank.com/certificates/iframe/e128d60ab287)', scope: '🎓 Academic' },
    { id: uid(), emoji: '📋', title: '**HackerRank SQL Certificate** — [View Certificate](https://www.hackerrank.com/certificates/iframe/a61045692af2)', scope: '🎓 Academic' },
    { id: uid(), emoji: '✍️', title: '**"Does AI Have Bias?" Essay** — Merit with Distinction', scope: '🎓 Academic' },
  ],
  badgeCategories: [
    {
      id: uid(),
      name: 'Languages',
      badges: [
        { id: uid(), label: 'Python', color: '3670A0', logo: 'python', logoColor: 'ffdd54' },
        { id: uid(), label: 'Swift', color: 'F54A2A', logo: 'swift', logoColor: 'white' },
        { id: uid(), label: 'SwiftUI', color: '0D96F6', logo: 'swift', logoColor: 'white' },
        { id: uid(), label: 'C++', color: '00599C', logo: 'c%2B%2B', logoColor: 'white' },
        { id: uid(), label: 'Arduino', color: '00979D', logo: 'arduino', logoColor: 'white' },
        { id: uid(), label: 'SQL', color: '4479A1', logo: 'mysql', logoColor: 'white' },
        { id: uid(), label: 'Markdown', color: '000000', logo: 'markdown', logoColor: 'white' },
      ],
    },
    {
      id: uid(),
      name: 'Engineering & CAD',
      badges: [
        { id: uid(), label: 'Onshape', color: '64bc4f', logo: 'onshape', logoColor: 'white' },
        { id: uid(), label: 'Fusion 360', color: 'FF6C00', logo: 'autodesk', logoColor: 'white' },
        { id: uid(), label: 'Techsoft 2D Design', color: '4B9CD3', logo: '', logoColor: 'white' },
        { id: uid(), label: '3D Printing', color: 'FF6F00', logo: '', logoColor: 'white' },
        { id: uid(), label: 'Laser Cutting', color: 'FF3C00', logo: '', logoColor: 'white' },
        { id: uid(), label: 'Electronics', color: 'F0DB4F', logo: '', logoColor: 'white' },
        { id: uid(), label: 'Soldering', color: 'C0C0C0', logo: '', logoColor: 'white' },
        { id: uid(), label: 'Elegoo', color: '0078D4', logo: 'elegoo', logoColor: 'white' },
        { id: uid(), label: 'Bambu Lab', color: '00AE42', logo: 'bambulab', logoColor: 'white' },
      ],
    },
    {
      id: uid(),
      name: 'AI & APIs',
      badges: [
        { id: uid(), label: 'Anthropic', color: '3C3C3C', logo: 'anthropic', logoColor: 'white' },
        { id: uid(), label: 'Ollama', color: '000000', logo: 'ollama', logoColor: 'white' },
        { id: uid(), label: 'OpenAI', color: 'F5F5F5', logo: 'openai', logoColor: '000000' },
        { id: uid(), label: 'Google Gemini', color: '4285F4', logo: 'google', logoColor: 'white' },
        { id: uid(), label: 'Grok', color: '111111', logo: 'xdotai', logoColor: 'white' },
        { id: uid(), label: 'NewsAPI', color: 'FF9900', logo: '', logoColor: 'white' },
        { id: uid(), label: 'Yahoo Finance', color: '6001D2', logo: 'yahoo', logoColor: 'white' },
        { id: uid(), label: 'Suno', color: '000000', logo: 'suno', logoColor: 'white' },
      ],
    },
    {
      id: uid(),
      name: 'Cloud & Hosting',
      badges: [
        { id: uid(), label: 'Vercel', color: '000000', logo: 'vercel', logoColor: 'white' },
        { id: uid(), label: 'Odoo', color: '7A92B2', logo: 'odoo', logoColor: 'white' },
        { id: uid(), label: 'Lovable', color: 'F24E6A', logo: 'heart', logoColor: 'white' },
        { id: uid(), label: 'GitHub Pages', color: '222222', logo: 'github', logoColor: 'white' },
      ],
    },
    {
      id: uid(),
      name: 'Design & Creative',
      badges: [
        { id: uid(), label: 'Canva', color: '00C4CC', logo: 'canva', logoColor: 'white' },
        { id: uid(), label: 'Photoshop', color: '31A8FF', logo: 'adobephotoshop', logoColor: 'white' },
        { id: uid(), label: 'Photopea', color: '18A497', logo: 'photopea', logoColor: 'white' },
        { id: uid(), label: 'Adobe', color: 'FF0000', logo: 'adobe', logoColor: 'white' },
      ],
    },
    {
      id: uid(),
      name: 'Platforms & Hardware',
      badges: [
        { id: uid(), label: 'Raspberry Pi', color: 'C51A4A', logo: 'raspberrypi', logoColor: 'white' },
        { id: uid(), label: 'VEX Robotics', color: 'ED1C24', logo: '', logoColor: 'white' },
        { id: uid(), label: 'macOS', color: '000000', logo: 'apple', logoColor: 'white' },
        { id: uid(), label: 'Windows', color: '0078D4', logo: 'windows11', logoColor: 'white' },
        { id: uid(), label: 'nVIDIA', color: '76B900', logo: 'nvidia', logoColor: 'white' },
        { id: uid(), label: 'Linux', color: 'FCC624', logo: 'linux', logoColor: 'black' },
        { id: uid(), label: 'Debian', color: 'A81D33', logo: 'debian', logoColor: 'white' },
      ],
    },
  ],
  featuredRepos: ['Pillgineers', 'Habs-Gliders-V5-Hub', '', ''],
  goals: [
    { id: uid(), text: 'Reach **1,000 GitHub followers**', completed: false, note: '' },
    { id: uid(), text: 'Continue contributing to **open source**', completed: false, note: '' },
    { id: uid(), text: 'Reach **Greenpower International Finals 2026** — back-to-back', completed: false, note: '' },
    { id: uid(), text: 'Ship a public project with **20+ stars**', completed: false, note: '' },
    { id: uid(), text: 'Become a **top 256 Github commiter in the UK** (Requires 350 followers)', completed: false, note: '' },
    { id: uid(), text: 'Create and deploy a **portfolio website**', completed: false, note: '' },
    { id: uid(), text: 'Win a **judged award at VEX World Championships**', completed: true, note: 'Won the Judges Award at VEX Worlds 2026' },
  ],
  goalsYear: '2026',
  shoutoutUsername: 'PanshulVempalli',
  shoutoutMessage: "go check out his profile! I do loads of projects with him!",
  showTrophies: true,
  showChart: true,
  showTools: true,
  showOpenToCollab: true,
};
